# -*- coding: utf-8 -*-
"""Python Data Analysis First project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14yMjQ1ldIVu_PIzJmo9uHGbgcSfmA-Nr
"""

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# python libraries imported

data= pd.read_csv("Diwali Sales Data.csv", encoding= 'unicode_escape')

data.shape

data.head()

data.tail(10)

data.describe()

data.info()

data.isnull()
#missing value

data.isnull().sum()

data.replace(' ',np.nan)

data.isnull().sum()*100/len(data)

data.info()

data['Amount'].fillna(data['Amount'].median())

data.info()

# drop blank columns
data.drop(['Status','unnamed1'],axis=1,inplace=True)

data.info()

data.dropna(axis=0)

data.info()

pd.isnull(data).sum()

data.columns

# rename column
data.rename(columns= {'Marital_Status':'Shaadi'}).head()

data.describe()

data[['Age', 'Orders', 'Amount']].describe()
# use describe() for specific column

# Gender

GenderData=data.groupby('Gender').sum()
GenderData

Value_count= data['Gender'].value_counts()
Value_count

# barplot for gender and its count

sns.set(rc={'figure.figsize':(3,3)})
bar=sns.countplot(x='Gender', data=data)

for bars in bar.containers:
    bar.bar_label(bars)

# gender vs total amount
data2= data.groupby(['Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(3,3)})
sns.barplot(x = 'Gender', y= 'Amount', data= data2)

sns.set(rc={'figure.figsize':(10,4)})
data3=sns.countplot(data=data,x="Age Group", hue= "Gender")

for bars in data3.containers:
    data3.bar_label(bars)

# total amount vs age group

data4= data.groupby(['Age Group'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(10,4)})
sns.barplot(x = 'Age Group', y= 'Amount', data=data4)

"""Top 10 State with No of orders """

sales_state = data.groupby(['State'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10)

sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data = sales_state, x = 'State',y= 'Orders')

# total amount/sales from top 10 states

sales_state = data.groupby(['State'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)

sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data = sales_state, x = 'State',y= 'Amount')

"""From above graphs we can see that most of the orders & total sales/amount are from Uttar Pradesh, Maharashtra and Karnataka respectively

Marital Status
"""

data5 = sns.countplot(data = data, x = 'Marital_Status')

sns.set(rc={'figure.figsize':(3,3)})
for bars in data5.containers:
    data5.bar_label(bars)

sales_state = data.groupby(['Marital_Status', 'Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(6,5)})
sns.barplot(data = sales_state, x = 'Marital_Status',y= 'Amount', hue='Gender')

"""From above graphs we can see that most of the buyers are married (women) and they have high purchasing power

Occupation
"""

sns.set(rc={'figure.figsize':(20,5)})
data6 = sns.countplot(data = data, x = 'Occupation')

for bars in data6.containers:
    data6.bar_label(bars)

sales_state = data.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Occupation',y= 'Amount')

"""From above graphs we can see that most of the buyers are working in IT, Healthcare and Aviation sector

Product Category
"""

sns.set(rc={'figure.figsize':(20,5)})
data7 = sns.countplot(data = data, x = 'Product_Category')

for bars in data7.containers:
    data7.bar_label(bars)

sales_state = data.groupby(['Product_Category'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Product_Category',y= 'Amount')

"""From above graphs we can see that most of the sold products are from Food, Clothing and Electronics category

Top Products
"""

sales_state = data.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,7)})
sns.barplot(data = sales_state, x = 'Product_ID',y= 'Orders')

# top 10 most sold products

fig1, ax1 = plt.subplots(figsize=(12,7))
data.groupby('Product_ID')['Orders'].sum().nlargest(10).sort_values(ascending=False).plot(kind='bar')

"""**Conclusion**

Married women age group 26-35 yrs from UP,  Maharastra and Karnataka working in IT, Healthcare and Aviation are more likely to buy products from Food, Clothing and Electronics category
"""
